INSERT INTO `marque` (`marque_id`, `marque_libelle`, `marque_logo`,`type_id`) VALUES
(1, 'Abarth', 'abarth.png','1'),
(2, 'Ac', 'ac.png','1'),
(3, 'Acrea', 'acrea.png','1'),
(4, 'Acura', 'acura.png','1'),
(5, 'Ad Tramontana', 'ad-tramontana.png','1'),
(6, 'Adler', 'adler.png','1'),
(7, 'Aixam', 'aixam.png','1'),
(8, 'Al Melling', 'al-melling.png','1'),
(9, 'Aleko', 'aleko.png','1'),
(10, 'Alfa Romeo', 'alfa-romeo.png','1'),
(11, 'Alpina', 'alpina.png','1'),
(12, 'Alpine Renault', 'alpine-renault.png','1'),
(13, 'Alvis', 'alvis.png','1'),
(14, 'Amc', 'amc.png','1'),
(15, 'Amphicar', 'amphicar.png','1'),
(16, 'Aptera Motors', 'aptera-motors.png','1'),
(17, 'Ariel', 'ariel.png','1'),
(18, 'Armstrong Siddeley', 'armstrong-siddeley.png','1'),
(19, 'Aro', 'aro.png','1'),
(20, 'Artega', 'artega.png','1'),
(21, 'Ascari', 'ascari.png','1'),
(22, 'Aston Martin', 'aston-martin.png','1'),
(23, 'Audi', 'audi.png','1'),
(24, 'Austin', 'austin.png','1'),
(25, 'Austin Healey', 'austin-healey.png','1'),
(26, 'Auto Union', 'auto-union.png','1'),
(27, 'Autobianchi', 'autobianchi.png','1'),
(28, 'Auverland', 'auverland.png','1'),
(29, 'Bee Automobiles', 'bee-automobiles.png','1'),
(30, 'Bellier', 'bellier.png','1'),
(31, 'Bentley', 'bentley.png','1'),
(32, 'Berliet', 'berliet.png','1'),
(33, 'Bertone', 'bertone.png','1'),
(34, 'Bitter', 'bitter.png','1'),
(35, 'Bizzarrini', 'bizzarrini.png','1'),
(36, 'Bmw', 'bmw.png','1'),
(37, 'Bollore', 'bollore.png','1'),
(38, 'Bongarini', 'bongarini.png','1'),
(39, 'Booxt', 'booxt.png','1'),
(40, 'Borgward', 'borgward.png','1'),
(41, 'Bowler', 'bowler.png','1'),
(42, 'Brabus', 'brabus.png','1'),
(43, 'Bremach', 'bremach.png','1'),
(44, 'Brilliance', 'brilliance.png','1'),
(45, 'Bristol', 'bristol.png','1'),
(46, 'Brooke Cars', 'brooke-cars.png','1'),
(47, 'Bugatti', 'bugatti.png','1'),
(48, 'Buick', 'buick.png','1'),
(49, 'Byd', 'byd.png','1'),
(50, 'Cadillac', 'cadillac.png','1'),
(51, 'Caparo', 'caparo.png','1'),
(52, 'Carbodies', 'carbodies.png','1'),
(53, 'Carbontech', 'carbontech.png','1'),
(54, 'Carver', 'carver.png','1'),
(55, 'Casalini', 'casalini.png','1'),
(56, 'Caterham', 'caterham.png','1'),
(57, 'Cg', 'cg.png','1'),
(58, 'Chatenet', 'chatenet.png','1'),
(59, 'Chery', 'chery.png','1'),
(60, 'Chevrolet', 'chevrolet.png','1'),
(61, 'China Automobile', 'china-automobile.png','1'),
(62, 'Chrysler', 'chrysler.png','1'),
(63, 'Citroen', 'citroen.png','1'),
(64, 'Clenet', 'clenet.png','1'),
(65, 'Commuter Cars', 'commuter-cars.png','1'),
(66, 'Connaught', 'connaught.png','1'),
(67, 'Courb', 'courb.png','1'),
(68, 'Dacia', 'dacia.png','1'),
(69, 'Daewoo', 'daewoo.png','1'),
(70, 'Daf', 'daf.png','1'),
(71, 'Daihatsu', 'daihatsu.png','1'),
(72, 'Daimler', 'daimler.png','1'),
(73, 'Dallara', 'dallara.png','1'),
(74, 'Dangel', 'dangel.png','1'),
(75, 'Darmont', 'darmont.png','1'),
(76, 'Datsun', 'datsun.png','1'),
(77, 'De Fremond', 'de-fremond.png','1'),
(78, 'De La Chapelle', 'de-la-chapelle.png','1'),
(79, 'De Lorean', 'de-lorean.png','1'),
(80, 'De Soto', 'de-soto.png','1'),
(81, 'De Tomaso', 'de-tomaso.png','1'),
(82, 'Delage', 'delage.png','1'),
(83, 'Delahaye', 'delahaye.png','1'),
(84, 'Deronda', 'deronda.png','1'),
(85, 'Devon', 'devon.png','1'),
(86, 'Dkw', 'dkw.png','1'),
(87, 'Dodge', 'dodge.png','1'),
(88, 'Dongfeng', 'dongfeng.png','1'),
(89, 'Donkervoort', 'donkervoort.png','1'),
(90, 'Donnet', 'donnet.png','1'),
(91, 'Dr Motor', 'dr-motor.png','1'),
(92, 'Ds', 'ds.png','1'),
(93, 'Due', 'due.png','1'),
(94, 'Duesenberg', 'duesenberg.png','1'),
(95, 'Eagle', 'eagle.png','1'),
(96, 'Ebro', 'ebro.png','1'),
(97, 'Edsel', 'edsel.png','1'),
(98, 'Elv', 'elv.png','1'),
(99, 'Erad', 'erad.png','1'),
(100, 'Estrima', 'estrima.png','1'),
(101, 'Exagon Motors', 'exagon-motors.png','1'),
(102, 'Excalibur', 'excalibur.png','1'),
(103, 'Facel Vega', 'facel-vega.png','1'),
(104, 'Fam Automobiles', 'fam-automobiles.png','1'),
(105, 'Faralli & Mazzanti', 'faralli-mazzanti.png','1'),
(106, 'Farbio', 'farbio.png','1'),
(107, 'Ferrari', 'ferrari.png','1'),
(108, 'Fiat', 'fiat.png','1'),
(109, 'Fioravanti', 'fioravanti.png','1'),
(110, 'Fisker', 'fisker.png','1'),
(111, 'Ford', 'ford.png','1'),
(112, 'Fornasari', 'fornasari.png','1'),
(113, 'Fso', 'fso.png','1'),
(114, 'Geely', 'geely.png','1'),
(115, 'Gillet', 'gillet.png','1'),
(116, 'Ginetta', 'ginetta.png','1'),
(117, 'Glas', 'glas.png','1'),
(118, 'Gmc', 'gmc.png','1'),
(119, 'Gme', 'gme.png','1'),
(120, 'Grandin', 'grandin.png','1'),
(121, 'Great Wall', 'great-wall.png','1'),
(122, 'Grecav', 'grecav.png','1'),
(123, 'Gumpert', 'gumpert.png','1'),
(124, 'Healey', 'healey.png','1'),
(125, 'Helem', 'hekem.png','1'),
(126, 'Heuliez', 'heuliez.png','1'),
(127, 'Hillman', 'hillman.png','1'),
(128, 'Holden', 'holden.png','1'),
(129, 'Hommell', 'hommell.png','1'),
(130, 'Honda', 'honda.png','1'),
(131, 'Hotchkiss', 'hotchkiss.png','1'),
(132, 'Howmet', 'howmet.png','1'),
(133, 'Hudson', 'hudson.png','1'),
(134, 'Humber', 'humber.png','1'),
(135, 'Hummer', 'hummer.png','1'),
(136, 'Hyundai', 'hyundai.png','1'),
(137, 'Imperial', 'imperial.png','1'),
(138, 'Infiniti', 'infiniti.png','1'),
(139, 'Innocenti', 'innocenti.png','1'),
(140, 'Innotech', 'innotech.png','1'),
(141, 'Intermeccanica', 'intermeccanica.png','1'),
(142, 'International', 'international?png','1'),
(143, 'Invicta', 'invicta.png','1'),
(144, 'Iso', 'iso.png','1'),
(145, 'Isorivolta', 'isorivolta.png','1'),
(146, 'Isuzu', 'isuzu.png','1'),
(147, 'Italcar', 'italcar.png','1'),
(148, 'Iveco', 'iveco.png','1'),
(149, 'Jaguar', 'jaguar.png','1'),
(150, 'Jdm Simpa', 'jdm-simpa.png','1'),
(151, 'Jeep', 'jeep.png','1'),
(152, 'Jensen', 'jensen.png','1'),
(153, 'Kassbohrer Setra', 'kassbohrer-setra.png','1'),
(154, 'Kia', 'kia.png','1'),
(155, 'Koenigsegg', 'koenigsegg.png','1'),
(156, 'Ktm', 'ktm.png','1'),
(157, 'Lada', 'lada.png','1'),
(158, 'Lagonda', 'lagonda.png','1'),
(159, 'Lamborghini', 'lamborghini.png','1'),
(160, 'Lancia', 'lancia.png','1'),
(161, 'Land Rover', 'land-rover.png','1'),
(162, 'Landwind', 'landwind.png','1'),
(163, 'Lantana', 'lantana.png','1'),
(164, 'Laraki', 'laraki.png','1'),
(165, 'Ldv', 'ldv.png','1'),
(166, 'Lexus', 'lexus.png','1'),
(167, 'Ligier', 'ligier.png','1'),
(168, 'Lincoln', 'lincoln.png','1'),
(169, 'Lister', 'lister.png','1'),
(170, 'Little', 'little.png','1'),
(171, 'Lola', 'lola.png','1'),
(172, 'London Taxi Company', 'london-taxi-company.png','1'),
(173, 'Loremo', 'loremo.png','1'),
(174, 'Lotus', 'lotus.png','1'),
(175, 'Lumeneo', 'lumeneo.png','1'),
(176, 'Mahindra', 'mahindra.png','1'),
(177, 'Man', 'man.png','1'),
(178, 'Marcos', 'marcos.png','1'),
(179, 'Martin', 'martin.png','1'),
(180, 'Marussia', 'marussia.png','1'),
(181, 'Maruti', 'maruti.png','1'),
(182, 'Maserati', 'maserati.png','1'),
(183, 'Matra', 'matra.png','1'),
(184, 'Maybach', 'maybach.png','1'),
(185, 'Mazda', 'mazda.png','1'),
(186, 'Mclaren', 'mclaren.png','1'),
(187, 'Mdi', 'mdi.png','1'),
(188, 'Mega', 'mega.png','1'),
(189, 'Melkus', 'melkus.png','1'),
(190, 'Mercedes', 'mercedes.png','1'),
(191, 'Mercedes-amg', 'mercedes-amg.png','1'),
(192, 'Mercury', 'mercury.png','1'),
(193, 'Mg', 'mg.png','1'),
(194, 'Mia Electric', 'mia-electric.png','1'),
(195, 'Microcar', 'microcar.png','1'),
(196, 'Mini', 'mini.png','1'),
(197, 'Mitsubishi', 'mitsubishi.png','1'),
(198, 'Mitsubishi Fuso', 'mitsubishi-fuso.png','1'),
(199, 'Mitsuoka', 'mitsuoka.png','1'),
(200, 'Monteverdi', 'monteverdi.png','1'),
(201, 'Morgan', 'morgan.png','1'),
(202, 'Morris', 'morris.png','1'),
(203, 'Mosler', 'mosler.png','1'),
(204, 'Mvs', 'mvs.png','1'),
(205, 'Mygale', 'mygale.png','1'),
(206, 'Nanjing', 'nanjing.png','1'),
(207, 'Nash', 'nash.png','1'),
(208, 'Neckar', 'neckar.png','1'),
(209, 'Newteon', 'newteon.png','1'),
(210, 'Nissan', 'nissan.png','1'),
(211, 'Noble', 'noble.png','1'),
(212, 'Nsu', 'nsu.png','1'),
(213, 'Numexia', 'numexia.png','1'),
(214, 'Oldsmobile', 'oldsmobile.png','1'),
(215, 'Opel', 'opel.png','1'),
(216, 'Osi', 'osi.png','1'),
(217, 'Packard', 'packard.png','1'),
(218, 'Pagani', 'pagani.png','1'),
(219, 'Panhard', 'panhard.png','1'),
(220, 'Panoz', 'panoz.png','1'),
(221, 'Panther', 'panther.png','1'),
(222, 'Pegaso', 'pegaso.png','1'),
(223, 'Perana', 'perana.png','1'),
(224, 'Peugeot', 'peugeot.png','1'),
(225, 'Pgo', 'pgo.png','1'),
(226, 'Piaggio', 'piaggio.png','1'),
(227, 'Pilbeam', 'pilbeam.png','1'),
(228, 'Plymouth', 'plymouth.png','1'),
(229, 'Polski', 'polski.png','1'),
(230, 'Pontiac', 'pontiac.png','1'),
(231, 'Porsche', 'porsche.png','1'),
(232, 'Proton', 'proton.png','1'),
(233, 'Protoscar', 'protoscar.png','1'),
(234, 'Qoros', 'qoros.png','1'),
(235, 'Quant', 'quant.png','1'),
(236, 'Radical', 'radical.png','1'),
(237, 'Reliant', 'reliant.png','1'),
(238, 'Renault', 'renault.png','1'),
(239, 'Renault Trucks', 'renault-trucks.png','1'),
(240, 'Rene Bonnet', 'rene-bonnet.png','1'),
(241, 'Reva', 'reva.png','1'),
(242, 'Reynard', 'reynard.png','1'),
(243, 'Riley', 'riley.png','1'),
(244, 'Rinspeed', 'rinspeed.png','1'),
(245, 'Rolls Royce', 'rolls-royce.png','1'),
(246, 'Ronart', 'ronart.png','1'),
(247, 'Rosengart', 'rosengart.png','1'),
(248, 'Rover', 'rover.png','1'),
(249, 'Russo-baltique', 'russo-baltique.png','1'),
(250, 'Saab', 'saab.png','1'),
(251, 'Saleen', 'saleen.png','1'),
(252, 'Salica', 'salica.png','1'),
(253, 'Salmson', 'salmson.png','1'),
(254, 'Samsung', 'samsung.png','1'),
(255, 'Santana', 'santana.png','1'),
(256, 'Saturn', 'saturn.png','1'),
(257, 'Savel', 'savel.png','1'),
(258, 'Saviem', 'saviem.png','1'),
(259, 'Sbarro', 'sbarro.png','1'),
(260, 'Scania', 'scania.png','1'),
(261, 'Scion', 'scion.png','1'),
(262, 'Seat', 'seat.png','1'),
(263, 'Secma', 'secma.png','1'),
(264, 'Shelby', 'shelby.png','1'),
(265, 'Shuanghuan', 'shuanghuan.png','1'),
(266, 'Simca', 'simca.png','1'),
(267, 'Singer', 'singer.png','1'),
(268, 'Sivax', 'sivax.png','1'),
(269, 'Skoda', 'skoda.png','1'),
(270, 'Smart', 'smart.png','1'),
(271, 'Sms', 'sms.png','1'),
(272, 'Sovamag', 'sovamag.png','1'),
(273, 'Spectre', 'spectre.png','1'),
(274, 'Spyker', 'spyker.png','1'),
(275, 'Srt', 'srt.png','1'),
(276, 'Ssangyong', 'ssangyong.png','1'),
(277, 'Ssc', 'ssc.png','1'),
(278, 'Studebaker', 'studebaker.png','1'),
(279, 'Stutz', 'stutz.png','1'),
(280, 'Subaru', 'subaru.png','1'),
(281, 'Sunbeam', 'sunbeam.png','1'),
(282, 'Suzuki', 'suzuki.png','1'),
(283, 'Talbot Simca', 'talbot-simca.png','1'),
(284, 'Tata', 'tata.png','1'),
(285, 'Teilhol', 'teilhol.png','1'),
(286, 'Tesla', 'tesla.png','1'),
(287, 'Think', 'think.png','1'),
(288, 'Toyota', 'toyota.png','1'),
(289, 'Trabant', 'trabant.png','1'),
(290, 'Triumph', 'triumph.png','1'),
(291, 'Tvr', 'tvr.png','1'),
(292, 'Ultima', 'ultima.png','1'),
(293, 'Umm', 'umm.png','1'),
(294, 'Vaillante', 'vaillante.png','1'),
(295, 'Van Hool', 'van-hool.png','1'),
(296, 'Vanden Plas', 'vaden-plas.png','1'),
(297, 'Vauxhall', 'vauxhall.png','1'),
(298, 'Venturi', 'venturi.png','1'),
(299, 'Veritas', 'veritas.png','1'),
(300, 'Vespa', 'vespa.png','1'),
(301, 'Virago', 'virago.png','1'),
(302, 'Volkswagen', 'volkswagen.png','1'),
(303, 'Volteis', 'volteis.png','1'),
(304, 'Volvo', 'volvo.png','1'),
(305, 'Volvo Trucks', 'volvo-trucks.png','1'),
(306, 'Westfield', 'westfield.png','1'),
(307, 'Wiesmann', 'wiesmann.png','1'),
(308, 'Willys', 'willys.png','1'),
(309, 'Wolseley', 'wolseley.png','1'),
(310, 'Xinyang', 'xinyang.png','1'),
(311, 'Zagato', 'zagato.png','1'),
(312, 'Zap', 'zap.png','1'),
(313, 'Zastava', 'zastava.png','1'),
(314, 'Zenn', 'zenn.png','1'),
(315, 'Zenvo', 'zenvo.png','1');